version: '3.7'
services:
  standalone_pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
     - 42099:80
    networks:
      - praxisbot
  standalone-db-main:
    image: postgres:13.4-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - ISDOCKER=cat
      - POSTGRES_DB=PRAXIS_BOT_DB
      - POSTGRES_USER=PRAXIS_BOT
      - POSTGRES_PASSWORD=PraxisPraxisPraxis
      - PGDATA=/Praxis/standalone-db/db_data
    volumes:
      - "./db_data:/Praxis/standalone-db/db_data"
      - "../logs:/Praxis/logs"
    networks:
      - praxisbot
      - praxisbot_inner
  standalone-db-manager:
    image: standalone-db
    ports:
      - 42002:42002
    environment:
      - ISDOCKER=cat
    networks:
      - praxisbot
    volumes:
      - "../logs:/Praxis/logs"
      - "../credentials:/Praxis/credentials"
      - "../config.py:/Praxis/config.py"
  praxis-app:
    container_name: praxis_app
    command: python manage.py runserver 0.0.0.0:85
    restart: always
    depends_on:
      - standalone-db-main
    networks:
      - praxisbot_inner
      - praxisbot_outer
    ports:
      - 8000:85
    env_file: ./user_client/v2/.env
    build: ./user_client/v2
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - 42808:85
    volumes:
      - ./user_client/v2/nginx/:/etc/nginx/conf.d
    networks:
      - praxisbot
      - praxisbot_outer
    depends_on:
      - praxis-app
networks:
  praxisbot:
    name: praxisbot
  praxisbot_inner:
    name: praxisbot_inner
  praxisbot_outer:
    name: praxisbot_outer